export const Images = {
  BACK_ICON: require('../assets/icons/backArrow/backArrow.png'),
  EYE_CLOSED: require('../assets/icons/eyeClosed/eyeClose.png'),
  EYE_OPEN: require('../assets/icons/eyeOpen/eyeOpen.png'),
  LIKE: require('../assets/images/like/like.png'),
  LOCK: require('../assets/images/lock/lock.png'),
  CHECK: require('../assets/icons/check/check.png'),
  CROSS: require('../assets/icons/cross/cross.png'),
  DOWN_ARROW: require('../assets/images/down/down.png'),
  UP_ARROW: require('../assets/icons/upArrow/upArrow.png'),
  PROFILE_IMAGE: require('../assets/images/profileImage/profileImage.png'),
  SYNC: require('../assets/icons/sync/sync.png'),
  PROFILE_PIC: require('../assets/icons/profilePic/profilepic.png'),
  LOG_OUT: require('../assets/icons/logOut/logout.png'),
  LETS_GO: require('../assets/icons/letsGoIcon/Car.png'),
  SMELLS_GOOD: require('../assets/icons/foodAppIcon/SmellGood.png'),
  YOU_TUBE: require('../assets/icons/youTubeIcon/Youtube.png'),
  NETFLIX: require('../assets/icons/netflixIcon/Netflix.png'),
  NETFLIX_INTRO: require('../assets/videos/NetflixIntro.mp4'),
  HOME_ICON: require('../assets/icons/homeIcon/home.png'),
  SHORTS: require('../assets/icons/shorts/shorts.png'),
  YOUTUBE_MORE: require('../assets/icons/ytMore/ytMore.png'),
  SUBSCRIPTION: require('../assets/icons/subscription/subscription.png'),
  LIBRARY: require('../assets/icons/library/library.png'),
  YOUTUBE_LOGO: require('../assets/icons/youtubeLogo/YoutubeLogo.png'),
};
